### ISSUE TITLE
Show the album information.

### ISSUE THREAD

**Issue by maxilevi** [RgtArRr/AtomPlayer#13]
Sometimes when a song play I would like to see which album is it from. Kind of like spotify does it. We could achieve this by doing a search on any song database. It would look cool if we also retrieved an image from google.

![image](https://user-images.githubusercontent.com/8160966/51796391-32c20100-21d0-11e9-80f9-1ffff79a4136.png)
See that spotify shows the album image at the left corner. We could do something like that.

**Comment by RgtArRr** [comment]
Now its available, the search is using the  song name and the word 'album', the first image match will be render as the image album/song
