### ISSUE TITLE
Instead of downloading 1 song at a time allow for queuing multiple ones.

### ISSUE THREAD

**Issue by maxilevi** [RgtArRr/AtomPlayer#6]
### Intent
Instead of adding a song from youtube and waiting till the download finishes to add another one we could add a song queue. 

### Design
We could maintain the current textbox and button, and change its text from "Download" to "Queue". We should also remove the progress bar and add a table element underneath showing the current download queue of songs. As something complementary we could show either a small progress bar for each table entry or the current one representing the current song being downloaded.
This could either be shown in the current tab or after clicking a special "Advanced Options" button, so as to not remove from the ease of usage of the player.

**Comment by RgtArRr** [comment]
c8e4ba425ab8fb8d87874a0d00be69ceb6db7b88
