### ISSUE TITLE
The shuffle option has too much randomness.

### ISSUE THREAD

**Issue by maxilevi** [RgtArRr/AtomPlayer#8]
## Problem
When the shuffle option is on the next song is determined at runtime, when the current one finishes. This gives an "equal chance" to every song including the ones that were already played. This makes it pretty annoying when the player rightfully replays the same song twice. 

## Possible Solution
Instead of determining the next song at runtime, one solution is to build a list of the songs and shuffle them so we guarantee that each one is played at least once but in a random order. One algorithm for shuffling is the [Fisher–Yates shuffle](https://en.wikipedia.org/wiki/Fisher–Yates_shuffle), here is a [JS Implementation](https://stackoverflow.com/a/2450976/3430546).

### Caveats
If we end up implementing the suggested solution, we should recreate the "shuffled song list" everytime a song is added/removed.

**Comment by RgtArRr** [comment]
5a563bc167bdeec36254f2a9421c2100ed4cdb0b
d149de2db4539a5a481e1718c59235389229d512
